config/routes.rb
Rails.application.routes.draw do

  match '*all' => "application#cors_preflight_check", via: :options

  get "dashboard" => "manager/administrators#dashboard", as: "dashboard"

  devise_for :administrators

  devise_scope :administrator do
    root to: "devise/sessions#new"
  end  

  namespace :manager do
    resources :administrators
  end
  
  resources :vendors do
    get 'review_payment', on: :member
  end

  resources :products, except: :show
  resources :purchases, only: [:create, :index, :update, :show] do
    collection do
      get :report
      post :report_settings
    end
  end

  resources :payments do
    collection do
      get :report
    end
  end


  resources :locations, only: [:index] 
  resources :devices, only: [:create, :update, :index, :show] do
    get 'recent_vendors', on: :member
    get 'recent_transactions', on: :member
  end

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:full_name]

  belongs_to :created_by, :class_name => "Administrator"
  
  def email_changed?
    false
  end

  def email_required?
    false
  end
  
end

app/controllers/manager/administrators_controller.rb
class Manager::AdministratorsController < ApplicationController
  
  helper_method :sort_column, :sort_direction

  before_action :load_administrator, only: [:edit, :update, :destroy]
  before_action :only_managers, except: :dashboard
  before_action :only_admin, only: :dashboard

  def dashboard
    @in_app_products = Product.order('products.order ASC').available_in_app
    @vendors_awaiting_payments = Vendor.has_unpaid_purchases
  end

  def index
    @administrators = Administrator.all
    @administrators = @administrators.order(sort_column + " " + sort_direction)
  end

  def new
    @administrator = Administrator.new
  end

  def edit
    @administrator.full_name = @administrator.full_name.titleize
  end

  def create
    @administrator = Administrator.new(administrator_params)
    @administrator.created_by = current_administrator
  
    if @administrator.save
      redirect_to manager_administrators_path, notice: 'Administrator was successfully created.'
    else
      render :new 
    end
  end

  def update
    @administrator.update_attributes(administrator_params)

    if @administrator.save
      redirect_to manager_administrators_path, notice: 'Administrator was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @administrator.destroy
      redirect_to manager_administrators_path, notice: 'Administrator was successfully destroyed.'
    else
      render :edit
    end
  end

  private

  def load_administrator
    @administrator = Administrator.find(params[:id])
  end

  def administrator_params
    if params[:administrator][:password].present? && params[:administrator][:password_confirmation].present?
      params.require(:administrator).permit(
        :full_name,
        :manager,
        :password,
        :password_confirmation
      )
    else
      params.require(:administrator).permit(
        :full_name,
        :manager
        )    
    end  
  end

  def sort_column
    Administrator.column_names.include?(params[:sort]) ? params[:sort] : "full_name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end  
end

app/helpers/manager/administrators_helper.rb
module Manager::AdministratorsHelper
end

app/views/manager/administrators/_form.html.erb
<%= form_for [:manager, @administrator] do |f| %>
  <% if @administrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
      <% @administrator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :full_name %><br />
        <%= f.text_field :full_name, autofocus: true, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :password %> <em>(8 characters minimum)</em><br />
        <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :manager, "Manager?" %>
        <%= f.check_box :manager %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.submit "Save", class: "btn btn-success pull-right" %>
        <% unless @administrator.new_record? %>
        <%= link_to 'Delete', manager_administrator_path(@administrator), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/manager/administrators/dashboard.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Unclaimed Payments</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-8 unclaimed-payments">
    <% if @vendors_awaiting_payments.length <= 0 %>
      <p>There are no unclaimed payments.</p>
    <% end %>
    <% @vendors_awaiting_payments.each do |vendor| %>
      <%= link_to vendor_path(vendor), class: 'vendor-card' do %>
      <div class=" awaiting-payments">
        <div class="profile-image-container">
          <% if !vendor.image.thumb.url.blank? %>
            <%= image_tag vendor.image.thumb.url %>
          <% else %>
            <%= image_tag 'vendor-default.svg' %>
          <% end %>
        </div>
        <div class="vendor-name"><%= vendor.name %></div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <h1>Current Products Showing In App</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-8 products-list">
    <% @in_app_products.each do |product| %>
      <%= link_to edit_product_path(product) do %>
      <div class="col-md-12 dashboard-product">
        <div class="col-md-12">
          <%= image_tag product.image.profile.url, height: 100 %>
        </div>
        <div class="col-md-12 product-title">
          <%= product.title %>
        </div>
      </div>
      <% end %>
    <% end %>    
  </div>
</div>

app/views/manager/administrators/edit.html.erb
<%= link_to raw("&larr; Back To Staff"), manager_administrators_path, class: 'back-button' %>

<h1>Edit Staff</h1>

<%= render 'form' %>

app/views/manager/administrators/index.html.erb
<h1>Staff</h1>

<%= link_to "Add Staff", new_manager_administrator_path, class: "btn btn-primary new-vendor-btn" %>

<div class="row">
  <div class="col-md-8">
    <table class="table">
      <thead>
        <tr>
          <th><%= sortable 'full_name', 'Name' %></th>
          <th><%= sortable 'manager', 'Role' %></th>
          <th><%= sortable 'created_by', 'Added By' %></th>
        </tr>
      </thead>
      <tbody>
        <% @administrators.each do |administrator| %>
          <tr class="vendor-row" data-link="<%= edit_manager_administrator_path(administrator) %>">
            <td><%= administrator.full_name.titleize %></td>
            <td><%= administrator.manager ? "Manager" : "Volunteer" %></td>
            <td><%= administrator.created_by.try { full_name.titleize } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>    
  </div>
</div>

app/views/manager/administrators/new.html.erb
<h1>New Administrator</h1>

<%= render 'form' %>