config/routes.rb
Rails.application.routes.draw do

  match '*all' => "application#cors_preflight_check", via: :options

  get "dashboard" => "manager/administrators#dashboard", as: "dashboard"

  devise_for :administrators

  devise_scope :administrator do
    root to: "devise/sessions#new"
  end  

  namespace :manager do
    resources :administrators
  end
  
  resources :vendors do
    get 'review_payment', on: :member
  end

  resources :products, except: :show
  resources :purchases, only: [:create, :index, :update, :show] do
    collection do
      get :report
      post :report_settings
    end
  end

  resources :payments do
    collection do
      get :report
    end
  end


  resources :locations, only: [:index] 
  resources :devices, only: [:create, :update, :index, :show] do
    get 'recent_vendors', on: :member
    get 'recent_transactions', on: :member
  end

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_and_belongs_to_many :products

  belongs_to :updated_by, :class_name => "Administrator"
  
  has_many :purchases
  has_many :locations
  has_many :payments
  accepts_nested_attributes_for :locations, reject_if: :all_blank, allow_destroy: true

  scope :has_unpaid_purchases, -> { includes(:purchases).where(purchases: { paid: false }) }

  validates :name, presence: true
  # validates :image, presence: true

  def unpaid_purchases
    purchases.where(paid: false)
  end

  def owed_amount
    unpaid_purchases.map { |purchase| purchase.total_amount }.sum if unpaid_purchases.any?
  end

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  helper_method :sort_column, :sort_direction
  
  before_action :only_admin, except: [:index, :show]
  before_action :only_managers, only: [:new, :edit]
  before_action :load_vendor, except: [:new, :create, :index]
  before_action :load_products, only: [:new, :edit, :create] 

  def index
    if params[:city]
      @locations = Location.includes(vendor: [:products, :locations]).where('city = ?', params[:city]);
      @vendors = @locations.map {|location| location.vendor}.uniq.reject { |vendor| !vendor }.sort! { |a,b| a.name.downcase <=> b.name.downcase }
    elsif params[:neighbourhood]
      @locations = Location.includes(vendor: [:products, :locations]).where('neighbourhood = ?', params[:neighbourhood]);
      @vendors = @locations.map {|location| location.vendor}.uniq.reject { |vendor| !vendor }.sort! { |a,b| a.name.downcase <=> b.name.downcase }
    else
      @vendors = Vendor.includes(:locations, :products).all
      @vendors = @vendors.order(sort_column + " " + sort_direction)
    end
    respond_to do |format|
      format.html
      format.json { render :json => @vendors.reject {|vendor| !vendor.in_app }.to_json(include: [:locations, :products]) }
    end
  end

  def show
    @last_payment = @vendor.payments.last
    respond_to do |format|
      format.html
      format.json { render :json => @vendor.to_json(include: [:locations, :products]) }
    end
  end

  def new
    @vendor = Vendor.new
    @vendor.locations.build
  end

  def create
    @vendor = Vendor.new(vendor_params)

    if @vendor.save
      redirect_to vendors_path
    else
      render :new
    end
  end

  def edit
    @vendor.locations.build
  end

  def update
    @vendor.update_attributes(vendor_params)
    @vendor.updated_by = current_administrator

    if @vendor.save
      redirect_to vendor_path(@vendor)
    else
      render :edit
    end
  end

  def destroy
    if @vendor.destroy
      redirect_to vendors_path
    else
      render :edit
    end
  end

  def review_payment
    @unpaid_purchases = @vendor.unpaid_purchases
  end

  protected

  def vendor_params
    params.require(:vendor).permit(
      :name,
      :badge_id,
      :image,
      :in_app,
      :has_back_issues,
      :locations_attributes => [:id, :name, :city, :neighbourhood, :cross_street, :hours, :description, :_destroy],
      :product_ids => []
    )
  end

  def load_vendor
    @vendor = Vendor.find(params[:id])
  end

  def load_products
    @products = Product.all
  end

  def sort_column
    Vendor.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end  

end

app/helpers/vendors_helper.rb
module VendorsHelper

  def neighbourhoods_for_dropdown
    cities_and_neighbourhoods = {
      'Vancouver' => [
        ['Arbutus Ridge', 'arbutus-ridge'],
        ['Downtown', 'downtown'],
        ['Dunbar Southlands', 'dunbar-southlands'],
        ['Fairview', 'fairview'],
        ['Grandview Woodland', 'grandview-woodland'],
        ['Hastings Sunrise', 'hastings-sunrise'],
        ['Kensington Cedar Cottage','kensington-cedar-cottage'],
        ['Kerrisdale', 'kerrisdale'],
        ['Killarney', 'killarney'],
        ['Kitsilano', 'kitsilano'],
        ['Marpole', 'marpole'],
        ['Mount Pleasant', 'mount-pleasant'],
        ['Oakridge', 'oakridge'],
        ['Renfrew Collingwood', 'renfrew-collingwood'],
        ['Riley Park', 'riley-park'],
        ['Shaughnessy', 'shaughnessy'],
        ['South Cambie', 'south-cambie'],
        ['Strathcona', 'strathcona'],
        ['Sunset', 'sunset'],
        ['West End', 'west-end'],
        ['West Point Grey', 'west-point-grey'],
      ],
      'Victoria' => [
        ['Burnside', 'burnside'],
        ['Downtown', 'downtown-victoria'],
        ['Fairfield', 'fairfield'],
        ['Fernwood', 'fernwood'],
        ['Gonzales', 'gonzales'],
        ['Hillside-Quadra', 'hillside-quadra'],
        ['James Bay', 'james-bay'],
        ['Jubilee', 'jubilee'],
        ['North Park', 'north-park'],
        ['Oaklands', 'oaklands'],
        ['Rockland', 'rockland'],
        ['Victoria Fraserview', 'victoria-fraserview'],
        ['Victoria West', 'victoria-west'],
      ]
    }   
  end

  def link_to_add_location(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, "#", class: 'add-location btn btn-primary', data: {id: id, fields: fields.gsub("\n", "")})
  end

  def vendor_neighbourhoods(vendor)
    vendor.locations.map(&:neighbourhood).uniq.join(", ")
  end

end

app/views/vendors/_form.html.erb
<% if @vendor.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">Please fix the following:</h3>
    </div>
    <div class="panel-body">           
      <ul>
        <% @vendor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end -%>
      </ul>
    </div>
  </div>
<% end -%>

<%= form_for @vendor, html: { multipart: true } do |f| %>

  <div class="row">
    <div class="row nested-row">
      <div class="col-md-2">
        <div class="form-group">
          <%= f.label :name, "Vendor Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.label :badge_id, "Badge ID" %>
          <%= f.number_field :badge_id, class: "form-control", rows: 3 %>
        </div>   
      </div>      
    </div>
    <div class="row nested-row">
      <div class="col-md-2">
        <div class="form-group">
          <%= f.check_box :in_app %>
          <%= f.label :in_app, "Show In App" %>
        </div>
      </div>     
      <div class="col-md-2">
        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image %>
        </div>
      </div>
    </div>     
  </div>

  <!-- <div class="row">
    <div class="col-md-12">
      <h3><%= f.label :product_ids, "Products Carried" %></h3>
    </div>
    <div class="col-md-6 vendor-products-form">
      <% @products.each do |product| %>
        <div class="col-md-12">
          <label>
            <%= f.check_box :product_ids, { multiple: true }, product.id, "" %> <%= product.title %>
          </label>
        </div>
      <% end %>
      <div class="col-md-12">
        <label>
          <%= f.check_box :has_back_issues %> Back Issues
        </label>
      </div>       
    </div>
  </div> -->

  <!-- <h3><%= f.label :locations, "Locations" %></h3>
  <div class="row">
    <div class="col-md-4 vendor-locations">
      <%= f.fields_for :locations do |builder| %>
        <div class="vendor-location-fields">
          <%= render 'location_fields', f: builder %>  
        </div>
      <% end %>
    </div>
  </div> -->

  <div class="row">
    <div class="col-md-4">
      <!-- <div class="col-md-12">
        <div class="form-group">
          <%= link_to_add_location "Add Location", f, :locations %>
        </div>
      </div>    -->
      <div class="col-md-12" style="margin-top: 25px;">
        <div class="form-group">
          <%= f.submit "Save", class: "btn btn-success pull-right" %>
          <%= link_to "Delete", vendor_path(@vendor), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this vendor?" } if (controller?('vendors') && action?('edit')) %>
        </div>      
      </div>  
    </div>   
  </div>

<% end %>

app/views/vendors/_location_fields.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="form-group">
      <%= f.label :name, "Location Name" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="form-group">
      <%= f.label :neighbourhood %>
      <%= f.hidden_field :city %>
      <%= f.select :neighbourhood, neighbourhoods_for_dropdown, {:prompt => "Neighbourhood"}, { class: "form-control neighbourhood-dropdown"} %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :hours %>
      <%= f.text_field :hours, class: "form-control" %>
    </div>
  </div>

  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :cross_street %>
      <%= f.text_field :cross_street, class: "form-control" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="form-group">
      <%= f.label :description, "Location Description" %>
      <%= f.text_area :description, class: "form-control", rows: 3 %>
    </div>
  </div> 
</div>

<div class="row">
  <div class="col-md-6">
    <%= f.check_box :_destroy, { class: "location-destroy-checkbox" } %>
    <%= f.label :_destroy, "Remove Location" %>
  </div>  
</div>

app/views/vendors/edit.html.erb
<%= link_to raw("&larr; Back To Vendor"), vendor_path(@vendor), class: 'back-button' %>

<h1>
  Edit Vendor
</h1>

<%= render "form" %>

app/views/vendors/index.html.erb
<h1>
  Vendors
</h1>

<%= link_to "Add New Vendor", new_vendor_path, class: "btn btn-primary new-vendor-btn" if current_administrator.try(:manager) %>

<div class="row">
  <div class="col-md-8">
    <table class="table">
      <thead>
        <tr class="vendor-list-header">
          <th><%= sortable 'badge_id', 'Badge' %></th>
          <th><%= sortable 'name' %></th>
          <th>Neighbourhoods</th>
          <th><%= sortable 'in_app', 'Visible In App?' %></th>
        </tr>
      </thead>
      <tbody>
        <% @vendors.each do |vendor| %>
          <tr class="vendor-row" data-link="<%= vendor_path(vendor) %>">
            <td><%= vendor.badge_id %></td>
            <td><%= vendor.name %></td>
            <td><%= vendor_neighbourhoods(vendor) %></td>
            <td><%= vendor.in_app ? "Yes" : "No" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>    
  </div>
</div>

app/views/vendors/new.html.erb
<h1>Create New Vendor</h1>      

<%= render "form" %>

app/views/vendors/review_payment.html.erb
<%= link_to raw("&larr; Back To Vendor"), vendor_path(@vendor), class: 'back-button' %>

<h1><%= @vendor.name %> - <%= purchases_date_range(@unpaid_purchases) %></h1>

<div class="row">
  <div class="col-md-8">
    <table class="table payout-table">
      <thead>
        <tr>
          <th>Ref</th>
          <th>Date</th>
          <th>Products</th>
          <th>Sub Total</th>
          <th>Tips</th>
          <th>Total</th>
          <th>Location</th>
        </tr>  
      </thead>
      <tbody>      
        <% @unpaid_purchases.each do |purchase| %>
          <tr>
            <td><%= purchase.transaction_id %></td>
            <td><%= purchase.created_at.strftime("%b #{purchase.created_at.day}, %Y") %></td>
            <td>
              <ul>
                <% products_titles_and_count(purchase).each do |product, count| %>
                  <li><%= count %> x <%= product %></li>
                <% end %>
              </ul>
            </td>
            <td><%= number_to_currency purchase.products_amount / 100.0 %></td>
            <td><%= number_to_currency purchase.tips / 100.0 %></td>
            <td><%= number_to_currency purchase.total_amount / 100.0 %></td>
            <td>Unavailable</td> <!-- Will Be Replaced With Geolocation And Will Be A Link To Google Maps -->
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<h1>Total Due: <%= number_to_currency @vendor.owed_amount / 100.0 %></h1>

<div class="payout-buttons">
  <a href="javascript:window.print();" class="btn btn-success">Print Payout Receipt</a>
  <%= link_to "Pay Vendor", purchase_path(@vendor), method: :put, class: "btn btn-success", data: { confirm: "#{@vendor.name}'s Sales\n#{purchases_date_range(@unpaid_purchases)} \nTotal Due: #{number_to_currency @vendor.owed_amount / 100.0 } \n\nOk to make this payment?"} %>
</div>

app/views/vendors/show.html.erb
<%= link_to raw("&larr; Back To Dashboard"), dashboard_path, class: 'back-button' %>
<%= link_to raw("&larr; Back To Vendors"), vendors_path, class: 'back-button' %>

<div class="row vendor-profile">
  <div class="col-md-4">
    <div class="row nested-row">
      <h1>
        <%= @vendor.name %>
        <div><small>Badge #<%= @vendor.badge_id %></small></div>
        <%= link_to "Edit Vendor", edit_vendor_path(@vendor), class: "btn btn-primary" if current_administrator.try(:manager) %>
      </h1>
      <h4><%= @vendor.in_app ? "Visible In App" : "Not Visible In App" %></h4>
    </div>

    <!-- To be replaced with transactions/payments info -->
    <div class="row nested-row vendor-earnings">
      <% if @vendor.owed_amount.present? %>
        <div class="col-md-6">
          <div class="col-md-5">
            <strong>Owing:</strong><br/> 
            <%= number_to_currency @vendor.owed_amount / 100.0 %>
          </div>
          <div class="col-md-4">
            <!-- Coming soon... -->
            <%= link_to 'Pay Vendor', review_payment_vendor_path(@vendor), class: "btn btn-success btn-sm vendor-payout" %>
          </div>
        </div>
      <% end %>
      <% if @last_payment.present? %>
        <div class="col-md-6">
          <strong>Last Payout:</strong><br/>
          <%=  @last_payment.created_at.strftime("%B #{@last_payment.created_at.day.ordinalize}, %Y") %> | <%= number_to_currency @last_payment.amount / 100.0 %><br/>  by <%= @last_payment.paid_by.present? ? @last_payment.paid_by.full_name.titleize : 'N/A' %>
        </div>
      <% end %>
    </div>

    <div class="row nested-row vendor-products">
      <h4>Products Carried</h4>
      <% if @vendor.products.present? %>
        <ul>
          <% @vendor.products.each do |product| %>
            <li><%= product.title %></li>
          <% end %>
          <% if @vendor.has_back_issues %>
            <li>Back Issues</li>
          <% end %>
        </ul>
      <% else %>
        <%= @vendor.name %> doesn't have any products
      <% end %>
    </div>

    <div class="row nested-row vendor-locations">
      <% @vendor.locations.each do |location| %>
        <div class="location-details">
          <div class="row">
            <div class="col-md-6">
              <h4>City: </h4>
              <p><%= location.city %></p>
            </div>  
            <div class="col-md-6">
              <h4>Neighbourhood: </h4>
              <p><%= location.neighbourhood %></p>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6">
              <h4>Name: </h4>
              <p><%= location.name %></p>
            </div>
            <div class="col-md-6">
              <h4>Cross Street: </h4>
              <p><%= location.cross_street %></p>
            </div>   
          </div>

          <div class="row">
            <div class="col-md-6">
              <h4>Description: </h4>
              <p><%= location.description %></p>
            </div>
            <div class="col-md-6">
              <h4>Hours:</h4>
              <p><%= location.hours %></p>
            </div>
          </div>
        </div>
      <% end %>      
    </div>

    <div class="row nested-row vendor-edited-by">
      <div class="col-md-12">
        <p><%= "Last edited by: #{@vendor.updated_by.full_name.titleize} on #{@vendor.updated_at.strftime("%B #{@vendor.updated_at.day.ordinalize} at %l:%M%p")}" if @vendor.updated_by.present? %></p>        
      </div>
    </div>

    <div class="row nested-row">
      <%= link_to "Purchases", report_purchases_path(vendor: @vendor.id), class: "btn btn-primary" %>
      <%= link_to "Payments", report_payments_path(vendor: @vendor.id), class: "btn btn-primary" %>
    </div>

  </div>
  <div class="col-md-4">
    <%= image_tag @vendor.image, class: "img-responsive profile-picture" %>
  </div>
</div>