config/routes.rb
Rails.application.routes.draw do

  match '*all' => "application#cors_preflight_check", via: :options

  get "dashboard" => "manager/administrators#dashboard", as: "dashboard"

  devise_for :administrators

  devise_scope :administrator do
    root to: "devise/sessions#new"
  end  

  namespace :manager do
    resources :administrators
  end
  
  resources :vendors do
    get 'review_payment', on: :member
  end

  resources :products, except: :show
  resources :purchases, only: [:create, :index, :update, :show] do
    collection do
      get :report
      post :report_settings
    end
  end

  resources :payments do
    collection do
      get :report
    end
  end


  resources :locations, only: [:index] 
  resources :devices, only: [:create, :update, :index, :show] do
    get 'recent_vendors', on: :member
    get 'recent_transactions', on: :member
  end

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_and_belongs_to_many :vendors

  after_update :only_one_in_app

  has_many :purchase_products
  has_many :purchases, through: :purchase_products

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image, presence: true
  # validates :in_app, presence: true

  scope :available_in_app, -> { where(in_app: true) } 

  def price_in_dollars
    if price.nil?
      0.00
    else
      "%0.2f" % (price / 100.0)
    end
  end

  protected

  def only_one_in_app
    # only if newspaper, multiple feature products can appear in the app at the same time.
    if self.category == 'Newspaper'
      Product.where.not(id: self.id).where(category: self.category).update_all(in_app: false) if self.in_app? && Product.where.not(id: self.id).where(category: self.category).available_in_app.any?  
    end
  end
end

app/controllers/products_controller.rb
require 'gcm'

class ProductsController < ApplicationController

  before_action do |controller|
    controller.send(:only_managers) unless controller.request.format.json?
  end

  before_action :load_product, except: [:index, :new, :create]

  def index
    @products = Product.order('products.order ASC').all
    respond_to do |format|
      format.html
      format.json { render :json => @products.available_in_app.to_json }
    end
  end

  def new
    @product = Product.new
  end

  def create
    the_params = product_params
    the_params[:price] = the_params[:price_in_dollars].to_f * 100.0
    the_params.delete :price_in_dollars
    @product = Product.new(the_params)
    
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def update
    the_params = product_params
    the_params[:price] = the_params[:price_in_dollars].to_f * 100.0 unless the_params[:price_in_dollars].nil?
    the_params.delete :price_in_dollars
    @product.assign_attributes(the_params)
    
    if params[:notify_update]
      @product.last_notification_date = DateTime.now
    end

    if @product.save
      # Push Notification
      if params[:notify_update]
        gcm = GCM.new(ENV['GCM_API_KEY'])
        eligible_devices = Device.where("push_notification_token is NOT NULL and push_notification_token != ''")
        registration_ids = eligible_devices.map {|device| device.push_notification_token}.uniq
        
        options = { 
          notification: { 
            title: "Street Sense Vendor Payments",
            body: "New #{@product.title} now available!",
            badge: 0,
            sound: "default" 
          },
          priority: 'high'
        }
        response = gcm.send(registration_ids, options)
        puts 'GCM response:'
        puts response
      end

      respond_to do |format|
        format.html { redirect_to products_path }
        format.json { render :json => @product.to_json }
      end
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      redirect_to products_path
    else
      render :new
    end
  end

  protected

  def product_params
    params.require(:product).permit(
      :title,
      :description,
      :price,
      :price_in_dollars,
      :image,
      :in_app,
      :category,
      :order
    )
  end

  def load_product
    @product = Product.find(params[:id])
  end  

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<% if @product.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">Please fix the following:</h3>
    </div>
    <div class="panel-body">           
      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end -%>
      </ul>
    </div>
  </div>
<% end -%>

<%= form_for @product, html: { multipart: true } do |f| %>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :description %> <span class="js_product_description_count description-count">(<span class="count"></span> characters)</span>
        <%= f.text_area :description, class: "form-control", rows: 3 %>
      </div>      
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <div class="form-group">
        <%= f.label :category %>
        <%= f.select :category, ["Feature", "Newspaper"], {:prompt => "Type"}, { class: "form-control"} %>  
      </div>
    </div>
    <div class="col-md-2">
      <div class="form-group">
        <%= f.label :price, "Price" %>
        <%= f.text_field :price_in_dollars, class: "form-control", placeholder: "$" %>
      </div>
    </div>       
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :image %>
        <p>Product images should be at least 350px wide with a ratio of 3:4. Ideal image size is 600x800 pixel.</p>
        <%= f.file_field :image %>  
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <div class="form-group">
        <%= f.label :in_app, "Show In App" %>
        <%= f.check_box :in_app %>
      </div>
    </div>       
    <div class="col-md-2">
      <div class="form-group">
        <%= f.label :order %>
        <%= f.select :order, options_for_select(["1", "2", "3", "4", "5"], @product.order), class: "form-control" %>
      </div>
    </div>       
  </div>
  
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= label_tag('notify_update', "Notify customers that a new item is available") %>
        <%= check_box_tag("notify_update") %> 
        <p class='info'>Last notification sent: 
          <% if @product.last_notification_date.blank? %>
            Never
          <% else %>
            <%= time_ago_in_words(@product.last_notification_date) %> ago
          <% end %>
        </p>
      </div>
    </div>       
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.submit "Save", class: "btn btn-success pull-right" %>
        <%= link_to "Delete", product_path(@product), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this product?" } if (controller?('products') && action?('edit')) %>
      </div>      
    </div>    
  </div>

<% end %>

app/views/products/edit.html.erb
<%= link_to raw("&larr; Back To Products"), products_path, class: 'back-button' %>

<h1>Edit Product</h1>

<%= render "form" %>

app/views/products/index.html.erb
<h1>Products</h1>

<%= link_to "Add New Product", new_product_path, class: "btn btn-primary new-vendor-btn" %>

<div class="products-container">
<% @products.each do |product| %>
  <div class="row product-details" data-product-id="<%= product.id %>">
    <div class="grab-handle">Move</div>
    <div class="col-md-2">
      <%= image_tag product.image.profile.url, class: "cover-image" %>
    </div>
    <div class="col-md-3">
      <h3><%= product.title %></h3>
      <p><%= number_to_currency product.price / 100.0 %></p>
      <p><%= product.in_app ? "Shown in app" : "Not shown in app" %></p>
      <%= link_to "Edit Product", edit_product_path(product), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
</div>

app/views/products/new.html.erb
<%= link_to raw("&larr; Back To Products"), products_path, class: 'back-button' %>

<h1>Add Product</h1>     

<%= render "form" %>