config/routes.rb
Rails.application.routes.draw do

  match '*all' => "application#cors_preflight_check", via: :options

  get "dashboard" => "manager/administrators#dashboard", as: "dashboard"

  devise_for :administrators

  devise_scope :administrator do
    root to: "devise/sessions#new"
  end  

  namespace :manager do
    resources :administrators
  end
  
  resources :vendors do
    get 'review_payment', on: :member
  end

  resources :products, except: :show
  resources :purchases, only: [:create, :index, :update, :show] do
    collection do
      get :report
      post :report_settings
    end
  end

  resources :payments do
    collection do
      get :report
    end
  end


  resources :locations, only: [:index] 
  resources :devices, only: [:create, :update, :index, :show] do
    get 'recent_vendors', on: :member
    get 'recent_transactions', on: :member
  end

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Street Sense App Manager</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if administrator_signed_in? %>
        <%= link_to raw("Street Sense<br/> <small>App Manager</small>"), dashboard_path, class: "navbar-brand" %>
      <% else %>
        <%= link_to raw("Street Sense<br/> <small>App Manager</small>"), root_path, class: "navbar-brand" %>
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if administrator_signed_in?  %>
          <li class="<%= "active" if (controller?('manager/administrators') && action?('dashboard')) %>"><%= link_to "Dashboard", dashboard_path %></li>
          <li class="<%= "active" if controller?('vendors') %>"><%= link_to "Vendors", vendors_path %></li>
          <% if current_administrator.try(:manager) %>
            <li class="<%= "active" if (controller?('products')) %>"><%= link_to "Products", products_path %></li>
            <li class="<%= "active" if (controller?('purchases')) %>"><%= link_to "Reports", report_purchases_path %></li>
            <li class="<%= "active" if (controller?('manager/administrators') && !action?('dashboard')) %>"><%= link_to "Staff", manager_administrators_path %></li>
          <% end %>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if administrator_signed_in? %>
          <li><%= link_to "Signed in as #{current_administrator.full_name.titleize}", edit_administrator_registration_path(current_administrator) %></li>
          <li><%= link_to "Sign Out", destroy_administrator_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_administrator_session_path %></li>
        <% end %>
      </ul>  

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
  <% if notice %>
    <div class="bg-warning alert">
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="bg-danger alert">
      <%= alert %>
    </div>
  <% end %>
  <%= yield %>  
</div>

</body>
</html>